package com.xwj.xwjnote3.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

import cn.bmob.v3.BmobObject;

/**
 * Entity mapped to table "NOTE".
 */
public class Note extends BmobObject implements Serializable {

    /**
     * Not-null value.
     */
    private String id;
    /**
     * Not-null value.
     */
    private String title;
    /**
     * Not-null value.
     */
    private String content;
    private boolean favorite;
    /**
     * Not-null value.
     */
    private String noteType;
    /**
     * Not-null value.
     */
    private java.util.Date createTime;
    /**
     * Not-null value.
     */
    private java.util.Date lastModifiedTime;
    /**
     * Not-null value.
     */
    private String userAuth;
    private boolean hasSync;

    public Note() {
    }

    public Note(String id) {
        this.id = id;
    }

    public Note(String id, String title, String content, boolean favorite, String noteType, java.util.Date createTime, java.util.Date lastModifiedTime, String userAuth, boolean hasSync) {
        this.id = id;
        this.title = title;
        this.content = content;
        this.favorite = favorite;
        this.noteType = noteType;
        this.createTime = createTime;
        this.lastModifiedTime = lastModifiedTime;
        this.userAuth = userAuth;
        this.hasSync = hasSync;
    }

    /**
     * Not-null value.
     */
    public String getId() {
        return id;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Not-null value.
     */
    public String getTitle() {
        return title;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Not-null value.
     */
    public String getContent() {
        return content;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setContent(String content) {
        this.content = content;
    }

    public boolean getFavorite() {
        return favorite;
    }

    public void setFavorite(boolean favorite) {
        this.favorite = favorite;
    }

    /**
     * Not-null value.
     */
    public String getNoteType() {
        return noteType;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setNoteType(String noteType) {
        this.noteType = noteType;
    }

    /**
     * Not-null value.
     */
    public java.util.Date getCreateTime() {
        return createTime;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setCreateTime(java.util.Date createTime) {
        this.createTime = createTime;
    }

    /**
     * Not-null value.
     */
    public java.util.Date getLastModifiedTime() {
        return lastModifiedTime;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setLastModifiedTime(java.util.Date lastModifiedTime) {
        this.lastModifiedTime = lastModifiedTime;
    }

    /**
     * Not-null value.
     */
    public String getUserAuth() {
        return userAuth;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setUserAuth(String userAuth) {
        this.userAuth = userAuth;
    }

    public boolean getHasSync() {
        return hasSync;
    }

    public void setHasSync(boolean hasSync) {
        this.hasSync = hasSync;
    }

}
